services:
  etcd1: &etcd
    image: ${PATRONI_TEST_IMAGE:-patroni01}
    network_mode: host
    extra_hosts:
      - "etcd1:10.1.3.19"
      - "etcd2:10.1.3.22"
      - "etcd3:10.1.3.24"
      - "patroni1:10.1.3.19"
      - "patroni2:10.1.3.22"
      - "patroni3:10.1.3.24"
    environment:
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: tutorial
      ETCD_UNSUPPORTED_ARCH: arm64
    container_name: demo-etcd1
    hostname: etcd1
    command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380

  patroni1:
    image: ${PATRONI_TEST_IMAGE:-patroni01}
    network_mode: host
    extra_hosts:
      - "etcd1:10.1.3.19"
      - "etcd2:10.1.3.22"
      - "etcd3:10.1.3.24"
      - "patroni1:10.1.3.19"
      - "patroni2:10.1.3.22"
      - "patroni3:10.1.3.24"
    env_file: docker/patroni.env
    hostname: patroni1
    container_name: demo-patroni1
    environment:
      ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
      PATRONI_SCOPE: demo
      PATRONI_NAME: patroni1
