services:
  etcd1:
    image: ${PATRONI_IMAGE:-patroni}
    network_mode: host
    extra_hosts:
      - "etcd1:10.1.3.19"
      - "etcd2:10.1.3.22"
      - "etcd3:10.1.3.24"
      - "patroni1:10.1.3.19"
      - "patroni2:10.1.3.22"
      - "patroni3:10.1.3.24"
    environment:
      ETCD_LISTEN_PEER_URLS: ${ETCD_LISTEN_PEER_URLS}
      ETCD_LISTEN_CLIENT_URLS: ${ETCD_LISTEN_CLIENT_URLS}
      ETCD_INITIAL_CLUSTER: ${ETCD_INITIAL_CLUSTER}
      ETCD_INITIAL_CLUSTER_STATE: ${ETCD_INITIAL_CLUSTER_STATE}
      ETCD_INITIAL_CLUSTER_TOKEN: ${ETCD_INITIAL_CLUSTER_TOKEN}
      # ETCD_UNSUPPORTED_ARCH: ${ETCD_UNSUPPORTED_ARCH}
    container_name: demo-etcd1
    hostname: etcd1
    command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380

  patroni1:
    image: ${PATRONI_TEST_IMAGE:-patroni}
    network_mode: host
    extra_hosts:
      - "etcd1:10.1.3.19"
      - "etcd2:10.1.3.22"
      - "etcd3:10.1.3.24"
      - "patroni1:10.1.3.19"
      - "patroni2:10.1.3.22"
      - "patroni3:10.1.3.24"
    env_file:
      - docker/patroni.env
    hostname: patroni1
    container_name: demo-patroni1
    environment:
      ETCDCTL_ENDPOINTS: ${ETCDCTL_ENDPOINTS}
      PATRONI_ETCD3_HOSTS: ${PATRONI_ETCD3_HOSTS}
      PATRONI_SCOPE: ${PATRONI_SCOPE}
      PATRONI_NAME: ${PATRONI_NAME1}
