version: "3"

services:
  haproxy:
    image: ${PATRONI_TEST_IMAGE:-patroni1}
    restart: always
    network_mode: host
    extra_hosts:
      - "etcd1:10.1.3.19"
      - "etcd2:10.1.3.22"
      - "etcd3:10.1.3.24"
      - "patroni1:10.1.3.19"
      - "patroni2:10.1.3.22"
      - "patroni3:10.1.3.24"
    env_file: docker/patroni.env
    hostname: haproxy
    container_name: demo-haproxy
    ports:
      - "5000:5000"
      - "5001:5001"
      - "7000:7000"
    command: haproxy
    environment:
      ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
      PATRONI_SCOPE: demo
