version: "2"

networks:
  demo:
    ipam:
      config:
        - subnet: 192.102.0.0/16

services:
  etcd2:
    image: ${PATRONI_TEST_IMAGE:-patroni}
    restart: unless-stopped
    ports:
      - "2379:2379"
      - "2380:2380"
    networks: [demo]
    ip: "192.102.0.102"
    environment:
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: etcd1=http://192.101.0.101:2380,etcd2=http://192.102.0.102:2380,etcd3=http://192.103.0.103:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: tutorial
      ETCD_UNSUPPORTED_ARCH: arm64ƒ
    container_name: demo-etcd2
    hostname: etcd2
    command: etcd --name etcd2 --initial-advertise-peer-urls http://192.102.0.102:2380

  patroni2:
    image: ${PATRONI_TEST_IMAGE:-patroni}
    restart: unless-stopped
    ports:
      - "8008:8008"
    networks: [demo]
    env_file: docker/patroni.env
    hostname: patroni2
    container_name: demo-patroni2
    environment:
      ETCDCTL_ENDPOINTS: http://192.101.0.101:2379,http://192.102.0.102:2379,http://192.103.0.103:2379
      PATRONI_ETCD3_HOSTS: "'192.101.0.101:2379','192.102.0.102:2379','192.103.0.103:2379'"
      PATRONI_SCOPE: demo
      PATRONI_NAME: patroni2
