services:
  etcd3:
    image: ${PATRONI_IMAGE:-patroni}
    network_mode: host
    extra_hosts:
      - "etcd1:${IP_HOST1}"
      - "etcd2:${IP_HOST2}"
      - "etcd3:${IP_HOST3}"
      - "patroni1:${IP_HOST1}"
      - "patroni2:${IP_HOST2}"
      - "patroni3:${IP_HOST3}"
    environment:
      ETCD_LISTEN_PEER_URLS: ${ETCD_LISTEN_PEER_URLS}
      ETCD_LISTEN_CLIENT_URLS: ${ETCD_LISTEN_CLIENT_URLS}
      ETCD_INITIAL_CLUSTER: ${ETCD_INITIAL_CLUSTER}
      ETCD_INITIAL_CLUSTER_STATE: ${ETCD_INITIAL_CLUSTER_STATE}
      ETCD_INITIAL_CLUSTER_TOKEN: ${ETCD_INITIAL_CLUSTER_TOKEN}
      ETCD_UNSUPPORTED_ARCH: ${ETCD_UNSUPPORTED_ARCH}
    container_name: demo-etcd3
    hostname: etcd3
    command: etcd --name etcd3 --initial-advertise-peer-urls http://etcd3:2380

  patroni3:
    image: ${PATRONI_TEST_IMAGE:-patroni}
    network_mode: host
    extra_hosts:
      - "etcd1:${IP_HOST1}"
      - "etcd2:${IP_HOST2}"
      - "etcd3:${IP_HOST3}"
      - "patroni1:${IP_HOST1}"
      - "patroni2:${IP_HOST2}"
      - "patroni3:${IP_HOST3}"
    env_file: docker/patroni.env
    hostname: patroni3
    container_name: demo-patroni3
    environment:
      ETCDCTL_ENDPOINTS: ${ETCDCTL_ENDPOINTS}
      PATRONI_ETCD3_HOSTS: ${PATRONI_ETCD3_HOSTS}
      PATRONI_SCOPE: ${PATRONI_SCOPE}
      PATRONI_NAME: ${PATRONI_NAME3}
