version: "3.9"

services:
  haproxy:
    image: haproxy:2.7
    network_mode: host
    extra_hosts:
      - "etcd1:10.1.3.19"
      - "etcd2:10.1.3.22"
      - "etcd3:10.1.3.24"
      - "patroni1:10.1.3.19"
      - "patroni2:10.1.3.22"
      - "patroni3:10.1.3.24"
    volumes:
      - ./haproxy:/haproxy-override
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - etcd1
      - etcd2
      - etcd3
      - patroni1
      - patroni2
      - patroni3
    ports:
      - "80:80"
      - "70:70" # haproxy admin console, login with user:pass